# Model configuration
model:
  model_id: "Qwen/Qwen2.5-Omni-7B"
  freeze_text_model: false
  audio_layer: -1
  bidirectional_audio: true
  linear_bias: -5.5
  dtype: "auto"

# Training configuration
training:
  epochs: 1
  effective_batch_size: 8
  learning_rate: 5.0e-6
  eta_min_scale: 0.1
 
# Dataset configuration
dataset:
  split: "train"
  repository: "enyoukai/AudioSet-Strong-Human-Sounds"

task:
  type: "SINGLE_WORD_TIMESTAMP"
  kwargs:
    key: "end"

# Loss configuration
loss:
  token_loss: false
  surrogate_loss: true
  surrogate_loss_weight: 1.0
  class_weighting: true
  poisson_loss: true

# System configuration
system:
  dataloader_num_workers: 1
  seed: 80

# Wandb configuration
wandb:
  entity: "taudio"