# Model configuration
model:
  model_id: "Qwen/Qwen2.5-Omni-3B"
  load_in_8bit: false
  freeze_text_model: false
  audio_layer: -1
  bidirectional_audio: true
  linear_bias: 0
  dtype: "float16"

# Training configuration
training:
  epochs: 1
  batch_size: 1
  grad_accumulation_steps: 8
  learning_rate: 5.0e-6
  eta_min_scale: 0.1
  optim_8bit: false
  
# Dataset configuration
dataset:
  split: "train"
  repository: "wjiaqi/taudio"
  padding: 0

task:
  type: "SPEAKER_COUNT"

# Loss configuration
loss:
  token_loss: true
  surrogate_loss: true
  surrogate_loss_weight: 0.05
  class_weighting: false
  poisson_loss: false

# System configuration
system:
  dataloader_num_workers: 1
  seed: 80

# Wandb configuration
wandb:
  entity: "taudio"