# Base experiment configuration
experiment_name: "[audioset][count]surrogate+optim_8bit+bidirectional_audio[poisson]"
description: "Surrogate loss, 8-bit optimizer, bidirectional audio, poisson loss"

# Model configuration
model:
  model_id: "Qwen/Qwen2.5-Omni-3B"
  load_in_8bit: false
  freeze_text_model: false
  audio_layer: -1
  bidirectional_audio: true
  linear_bias: -4

# Training configuration
training:
  epochs: 1
  batch_size: 1
  grad_accumulation_steps: 32
  learning_rate: 5.0e-6
  eta_min_scale: 0.1
  optim_8bit: true

# Dataset configuration
dataset:
  split: "train"
  repository: "enyoukai/AudioSet"
  padding: 0

# Task configuration
task:
  type: "SPEAKER_COUNTING"
  
# Loss configuration
loss:
  class_weighting: false
  surrogate_loss: true
  token_loss: false
  surrogate_loss_weight: 1.0
  poisson_loss: true

# System configuration
system:
  dataloader_num_workers: 1
  seed: 80
  save_checkpoints: true

# Wandb configuration
wandb:
  entity: "taudio"
  project: "Train"
  tags: ["surrogate", "optim_8bit", "bidirectional_audio", "speaker_counting", "padding_0", "poisson"] 