# Base experiment configuration
experiment_name: "[librispeech][qwen3b][token]"
description: "Token loss"

# Model configuration
model:
  model_id: "Qwen/Qwen2.5-Omni-3B"
  load_in_8bit: false
  freeze_text_model: false
  audio_layer: -1
  bidirectional_audio: false
  linear_bias: 0
  dtype: "auto"

# Training configuration
training:
  epochs: 1
  batch_size: 1
  grad_accumulation_steps: 32
  learning_rate: 5.0e-6
  eta_min_scale: 0.1
  optim_8bit: false

# Dataset configuration
dataset:
  split: "train_clean_100"
  repository: "gilkeyio/librispeech-alignments"
  padding: 0

# Task configuration
task:
  type: "SINGLE_WORD_TIMESTAMP"
  
# Loss configuration
loss:
  class_weighting: false
  surrogate_loss: false
  token_loss: true
  surrogate_loss_weight: 1.0
  poisson_loss: false

# System configuration
system:
  dataloader_num_workers: 1
  seed: 80
  save_checkpoints: true

# Wandb configuration
wandb:
  entity: "taudio"
  project: "Train"
  tags: ["token", "padding_0"] 