# Base experiment configuration
experiment_name: "[librispeech]surrogate+optim_8bit+class_weighting[end]"
description: "Surrogate loss, 8-bit optimizer, class weighting, end key"

# Model configuration
model:
  model_id: "Qwen/Qwen2.5-Omni-3B"
  load_in_8bit: false
  freeze_text_model: false
  audio_layer: -1

# Training configuration
training:
  epochs: 1
  batch_size: 1
  grad_accumulation_steps: 8
  learning_rate: 5.0e-6
  eta_min_scale: 0.1
  optim_8bit: true
  
# Dataset configuration
dataset:
  split: "train_clean_100"
  key: "end"
  repository: "gilkeyio/librispeech-alignments"
  
# Loss configuration
loss:
  token_loss: false
  surrogate_loss: true
  class_weighting: true
  surrogate_loss_weight: 1.0

# System configuration
system:
  dataloader_num_workers: 8
  seed: 80

# Wandb configuration
wandb:
  entity: "taudio"
  project: "Train"
  tags: ["surrogate", "optim_8bit", "end"] 
