# End prediction experiment configuration
experiment_name: "end_prediction"
description: "Experiment for predicting word end times instead of start times"

# Model configuration
model:
  model_id: "Qwen/Qwen2.5-Omni-3B"
  load_in_8bit: false
  freeze_text_model: false
  audio_layer: 18

# Training configuration
training:
  epochs: 1
  batch_size: 1
  grad_accumulation_steps: 8
  learning_rate: 5e-6
  eta_min_scale: 0.1
  optim_8bit: true
  
# Dataset configuration
dataset:
  split: "train_clean_100"
  key: "end"  # predicting end times instead of start
  
# Loss configuration
loss:
  class_weighting: true
  surrogate_loss: true
  token_loss: true
  surrogate_loss_weight: 0.2

# System configuration
system:
  dataloader_num_workers: 8
  seed: 80

# Wandb configuration
wandb:
  entity: "taudio"
  project: "Train"
  tags: ["end_prediction", "experiment"] 